package com.spring.movie.model;

import java.util.Date;

public class fenyeVideoSource {
	  private  Integer  total;
    public Integer getTotal() {
		return total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.videoUrl
     *
     * @mbggenerated
     */
    private String videourl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.flashUrl
     *
     * @mbggenerated
     */
    private String flashurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.htmlUrl
     *
     * @mbggenerated
     */
    private String htmlurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.commonUrl
     *
     * @mbggenerated
     */
    private String commonurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.imgUrl
     *
     * @mbggenerated
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.playNum
     *
     * @mbggenerated
     */
    private Integer playnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.score
     *
     * @mbggenerated
     */
    private Double score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.briefIntroduce
     *
     * @mbggenerated
     */
    private String briefintroduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.publishDate
     *
     * @mbggenerated
     */
    private Date publishdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.leadRole
     *
     * @mbggenerated
     */
    private String leadrole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.director
     *
     * @mbggenerated
     */
    private String director;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.cDate
     *
     * @mbggenerated
     */
    private Date cdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.id
     *
     * @return the value of video_source.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.id
     *
     * @param id the value for video_source.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.videoUrl
     *
     * @return the value of video_source.videoUrl
     *
     * @mbggenerated
     */
    public String getVideourl() {
        return videourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.videoUrl
     *
     * @param videourl the value for video_source.videoUrl
     *
     * @mbggenerated
     */
    public void setVideourl(String videourl) {
        this.videourl = videourl == null ? null : videourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.flashUrl
     *
     * @return the value of video_source.flashUrl
     *
     * @mbggenerated
     */
    public String getFlashurl() {
        return flashurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.flashUrl
     *
     * @param flashurl the value for video_source.flashUrl
     *
     * @mbggenerated
     */
    public void setFlashurl(String flashurl) {
        this.flashurl = flashurl == null ? null : flashurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.htmlUrl
     *
     * @return the value of video_source.htmlUrl
     *
     * @mbggenerated
     */
    public String getHtmlurl() {
        return htmlurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.htmlUrl
     *
     * @param htmlurl the value for video_source.htmlUrl
     *
     * @mbggenerated
     */
    public void setHtmlurl(String htmlurl) {
        this.htmlurl = htmlurl == null ? null : htmlurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.commonUrl
     *
     * @return the value of video_source.commonUrl
     *
     * @mbggenerated
     */
    public String getCommonurl() {
        return commonurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.commonUrl
     *
     * @param commonurl the value for video_source.commonUrl
     *
     * @mbggenerated
     */
    public void setCommonurl(String commonurl) {
        this.commonurl = commonurl == null ? null : commonurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.imgUrl
     *
     * @return the value of video_source.imgUrl
     *
     * @mbggenerated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.imgUrl
     *
     * @param imgurl the value for video_source.imgUrl
     *
     * @mbggenerated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.playNum
     *
     * @return the value of video_source.playNum
     *
     * @mbggenerated
     */
    public Integer getPlaynum() {
        return playnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.playNum
     *
     * @param playnum the value for video_source.playNum
     *
     * @mbggenerated
     */
    public void setPlaynum(Integer playnum) {
        this.playnum = playnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.score
     *
     * @return the value of video_source.score
     *
     * @mbggenerated
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.score
     *
     * @param score the value for video_source.score
     *
     * @mbggenerated
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.title
     *
     * @return the value of video_source.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.title
     *
     * @param title the value for video_source.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.briefIntroduce
     *
     * @return the value of video_source.briefIntroduce
     *
     * @mbggenerated
     */
    public String getBriefintroduce() {
        return briefintroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.briefIntroduce
     *
     * @param briefintroduce the value for video_source.briefIntroduce
     *
     * @mbggenerated
     */
    public void setBriefintroduce(String briefintroduce) {
        this.briefintroduce = briefintroduce == null ? null : briefintroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.type
     *
     * @return the value of video_source.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.type
     *
     * @param type the value for video_source.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.publishDate
     *
     * @return the value of video_source.publishDate
     *
     * @mbggenerated
     */
    public Date getPublishdate() {
        return publishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.publishDate
     *
     * @param publishdate the value for video_source.publishDate
     *
     * @mbggenerated
     */
    public void setPublishdate(Date publishdate) {
        this.publishdate = publishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.leadRole
     *
     * @return the value of video_source.leadRole
     *
     * @mbggenerated
     */
    public String getLeadrole() {
        return leadrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.leadRole
     *
     * @param leadrole the value for video_source.leadRole
     *
     * @mbggenerated
     */
    public void setLeadrole(String leadrole) {
        this.leadrole = leadrole == null ? null : leadrole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.director
     *
     * @return the value of video_source.director
     *
     * @mbggenerated
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.director
     *
     * @param director the value for video_source.director
     *
     * @mbggenerated
     */
    public void setDirector(String director) {
        this.director = director == null ? null : director.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.area
     *
     * @return the value of video_source.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.area
     *
     * @param area the value for video_source.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.cDate
     *
     * @return the value of video_source.cDate
     *
     * @mbggenerated
     */
    public Date getCdate() {
        return cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.cDate
     *
     * @param cdate the value for video_source.cDate
     *
     * @mbggenerated
     */
    public void setCdate(Date cdate) {
        this.cdate = cdate;
    }
}