package com.spring.movie.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.spring.movie.model.VideoSource;


public interface VideoSourceMapper {
	
	//分页查找
	List<VideoSource> selectByPage(@Param(value="startPos") int startPos,@Param(value="pageSize") int pageSize);
	
	//查找记录总数
    public int getTotalPage();
    
    public VideoSource getById(long id);
    
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbggenerated
     */
    int insert(VideoSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbggenerated
     */
    int insertSelective(VideoSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbggenerated
     */
   
    
    VideoSource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbggenerated
     */
  

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VideoSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VideoSource record);
}